---
# tasks file for apache
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Allow Apache on port 80 on the firewall
  become: true
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Enable UFW
  become: true
  community.general.ufw:
    state: enabled
    policy: allow

- name: Install Apache2
  become: true
  apt: name=apache2 state=latest

- name: Start Apache2
  systemd:
    name: apache2
    state: started
